Update Dockerfile
WARNING: The following packages cannot be authenticated!
  maven3
E: There are problems and -y was used without --force-yes
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get -y install maven3' returned a non-zero code: 100